version: '3.8'

services:
  db:
    image: postgres:12.2
    container_name: 'db'
    environment:
      POSTGRES_DB: 'blog_development'
      POSTGRES_USER: 'blog'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - $PWD/blog-data :/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always

  app:
    build: .
    container_name: 'app'
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - db

